# ==========================================================
# Flow
# ==========================================================
flow:
  initialize: false
  extract_features: true
  feature_normalizer: true
  train_system: true
  test_system: true
  evaluate_system: true

# ==========================================================
# General
# ==========================================================
general:
  development_dataset: TUTAcousticScenes_2016_DevelopmentSet
  challenge_dataset: TUTAcousticScenes_2016_EvaluationSet

  overwrite: true              # Overwrite previously stored data

# ==========================================================
# Paths
# ==========================================================
path:
  data:  ../../../../saved/data/

  base: system/baseline_dcase2016_task1/
  features: ../../../../../../saved/features/2016/traps26/features/
  feature_normalizers: ../../../../../../saved/features/2016/traps26/feature_normalizers/


  models: acoustic_models/
  results: evaluation_results/

  challenge_results: challenge_submission/task_1_acoustic_scene_classification/

# ==========================================================
# Feature extraction
# ==========================================================
features:
  method: traps

  fs: 44100
  win_length_seconds: 0.04
  hop_length_seconds: 0.02

  include_mfcc0: true           #
  include_delta: true           #
  include_acceleration: true    #

  mfcc:
    window: hamming_asymmetric  # [hann_asymmetric, hamming_asymmetric]
    n_mfcc: 20                  # Number of MFCC coefficients
    n_mels: 40                  # Number of MEL bands used
    n_fft: 2048                 # FFT length
    fmin: 0                     # Minimum frequency when constructing MEL bands
    fmax: 22050                 # Maximum frequency when constructing MEL band
    htk: false                  # Switch for HTK-styled MEL-frequency equation

  mfcc_delta:
    width: 9

  mfcc_acceleration:
    width: 9

  lfcc: !!null

  traps: 
    band: 26
    window: 101

# ==========================================================
# Classifier
# ==========================================================
classifier:
  method: dnn                   # The system supports only gmm
  parameters: !!null            # Parameters are copied from classifier_parameters based on defined method

classifier_parameters:
  gmm:
    n_components: 16            # Number of Gaussian components
    covariance_type: diag       # [diag|full] Diagonal or full covariance matrix
    random_state: 0
    thresh: !!null
    tol: 0.001
    min_covar: 0.001
    n_iter: 40
    n_init: 1
    params: wmc
    init_params: wmc

  dnn:
    hidden_units: [100,100,100]
    steps: 1000
    batch_size: 1024
    learning_rate: 0.05
    n_classes: 15
