fs: 44100
hash: 9b1279bafc66591bb2d3720db5fdef88
hop_length_seconds: 0.02
include_acceleration: false
include_delta: false
include_mfcc0: true
lpgd:
  lp_order: 20
  nfft: 2048
mfcc:
  fmax: 22050
  fmin: 0
  hop_length: 882
  htk: false
  n_fft: 2048
  n_mels: 40
  n_mfcc: 20
  win_length: 1764
  window: hamming_asymmetric
mfcc_acceleration:
  width: 9
mfcc_delta:
  width: 9
win_length_seconds: 0.04
